travis:
  secure:
    BINSTAR_TOKEN: f882hS2wyiMODbc/elY7M9L+OjewreF0yDL6C64/kz+uZ7Z7EcFTIbFSTyKfPR1dK2R/vifCpkjLi5YapboSF2etc8r4TSDVJPttVBvztZD8m2ql3297HfD893KD30jqL0yA+iQjZ15KXe4Caw8isF4PGukkA6lJTmwJarJmAtIs9SUJOjN4WNR49g0twiASlrRpHH4OTeEWAnVbiziSHioaENC34fF/Mm8O1wkf4EEmmNBGGJWOhIsKN+9BRbxKjud9eZC32xDFHnJshBu/Cm5oevxKr+BoyFWNb1MbTtpuaVdA8hRKux3Gxx0fHbh67XLNY1906IhESn9rtT1bcJ5Or+JQamkeboSFvh9fc5WKCekhE2OQfUvFtYMic3FPR2PMcXMrC70IfiM5FgPAp8rNYI1TxZ+mxwcve+l+fFsfyBJyRl3p8tG5s7IiLr0fM5TenBEu/9WdihdAgPqXRDLoxcIAkKQaM/PF/mHA8EhKYGtgk4a6sfRsDBMue16rUI/4Eh5jd/RFoFM1bv48HLffUL871xWuUTed4k6fwo+kvErrCxtsXZ8ENTgkKCOAxaZKRVjhMW+IMD9eTV1is/RUg4lrludDrDaE4EUrVE4vwzV9Cuqzbs/pxSplglqYqdhuPUirQEyY8hgVIWIHKj8fqgVUkDY1HG8dFTzd0co=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
