travis:
  secure:
    BINSTAR_TOKEN: UZTepoza8nkxdAl1MxG/BJ6HbhPWp4CnKDMRwuNAnpuibkLolJ4uumdeQpfJRwYzq7goo3ogQuCkgSSxgx3ovDwPzDAKQ0bminGQtXRmW5exjhNS14CERt5VnYH/Spa6DCmRO2DoH2kqxavo6Eny0UBUNKIQb6pEYNx1p+uN8c7NJV4sRvQoB6cOeSKFIoo/8mSp/vYJRZPQGarnUgNva0eewrnZNJ86mJyqxxDMlQDMrbZCBv91Hf/LSVJi6+2/5LcAvSqsO7iD2cawQKU1AeqvLlH2iJC11Uq4RrJXFU13tJiUQz8OobYI1iO6VuqgZ09D23XtRnPgBv9PibGnyML+RzDE4MTN4hbjuF3+tHCj2Qdd72sq4qc2hHA2/3je5MMAvvVFM/+dlSOFyT3XUDOPUm0MnIgWo1huoVgAM18s4LkO4399b1nd/FFGHaf7cGiOEPKbCLFC0+JpRUupYO9RurVuS/48iN/zmpj+s45w9jkPTiCHPxmhYi/uqub90gITR6Z8LDrnfWX6ocHehRdkNRsMU6N36UipeldfBMWORxXSq93CrFX01UFqlLrMq5sLLhaP3qos1UeeEaOeIdweH1q7uYeRNg62xAGF0G01OiHLpShqsDvzTJ2PVMOYXJRt1rrcIAfSnZv8bmjLwZx3bsuTbWMr9a3n1AFe6BU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
