travis:
  secure:
    BINSTAR_TOKEN: OIBZS6l56SOsQsxiohknUU4WNSFXk5dmWfqXqk6V50xq0s4GBsl2iJxN3KP9v9AmfxvixvLQp5EZhHSyyOvM9nLV/+2CcLVTNHyrpw4LP93OCfQn6S0qfXxwHFftz3G/2hlF1EIy4clrWoUyOqiyWGChfhlP0xFbasJMA/VP+UQJ4vK55u3TIMK9apnXZKQIxqUZ8Ie5ot+tDPJha+EDLmKcj3hcrtFSOfPd/X75pPVUnyGGpyL4wYL/PaYYwRTPJ76poWfUhwnzGF3bAPnCKIeJ39Ibnyk9Ab5pSP9nNTR8HQosvsDfjcCo1S8DgKHPRTdVOEwy/oHX5mEQwbG42wNGkmupQErB5bs37ozTe/UHqW3g3g0AfIIpq7AngQhsytSGsZE8aZLcq8wTQI9U5ybSomyK4Vdfoy+gQ7rsM6KAFfDIlX3vMqdrCGeDfJqm8eyBpQn7TolH+gP6QFzTyR8KRZoGteIcGEVHpFVM0/w92R2yLJSrBQxZxD0W3k4GPXKXcq+D7pyequwq+wzU2geIxEGXJL9Aav5zj7ZN/BsSf6Ewiy8S2d3w1E9XSjauIhRUw9rdRCjy0R+xtsbuifxohBhwibjZTh/nzrpUfRwDtdvGpWe+RJTXiJDTplWnozHnYgD5DjB7K1BSiOPsKBcg3dIBvo/K1aTCcm6qksU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
