travis:
  secure:
    BINSTAR_TOKEN: Jb/pcOscAz8R07Io4kmyERGz+xLpQLg0/QqHnmhw2o57OrPdmtgglJi/tpmPeeYtd0KRcMuNrmdtesym7wCrh96YW0A9tY4qlR09Rgq9FYp02RnUy/mZcoNQ2hDpJUa1EELNiHeqSSUD2pkNLMzr1zIzJTS9/P8YjuoYUBknzYHAGUcGIEmZX8YNhn4qxp+C5O9Tck0Xdyiijjm1iwJS38mumuA2vpxa7dFdjzd8MnrCnq1ckps4t6bMUFTEW+2AVVRF/yATjustjMQMWrM0SNBs6jz5sP002mCStVyIsvAj17v2h9AVvYkwkvXfKyH5mcYejSyXHn/vmATMepfPIyFv99ZkSwE8iXHrVCDYHTBimS64lTT5TK0Pl3zmSqUq7Ft+ebdQeXj5KlS8w0M3MqsFbnRCUo8Cfr9E5SRfeIShoDsLUNPk26HVHZKUuHE9BhLP8tKyYIwdMdcqWxPtTO7hI9KqGyP/WpQG2OKy7iZVmP3j/Rt9WLm7guBvjM/e2UGzB2WXeiYeXBOX0prhwLpC+ednJ0ZW6QEgOVJwPAoRJ73nRNleafPZ6SowxSsgrpyI2O3Gn2SvhvbsIfWNimWcwLIkNTV2udYrJ+NmzIKPo6RLp00geSIYatpJFodeqy4kmdkS2SaBc8OYnRI0+cUXdZW9eXgXZbRlJkzwTM8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
